"""add pandascore_id to teams and leagues

Revision ID: 6e01e2bf57ac
Revises: 8e95b1a2f819
Create Date: 2026-06-11 18:09:23.693862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e01e2bf57ac'
down_revision: Union[str, Sequence[str], None] = '8e95b1a2f819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
