"""add_number_of_games_to_matches

Revision ID: 6f9c7e305be0
Revises: aeb214e8e170
Create Date: 2026-05-30 09:42:15.777635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9c7e305be0'
down_revision: Union[str, Sequence[str], None] = 'aeb214e8e170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('number_of_games', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'number_of_games')
    # ### end Alembic commands ###
