"""add pandascore_id to teams and leagues

Revision ID: 8e95b1a2f819
Revises: b746d7e4d267
Create Date: 2026-06-11 18:05:04.928713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e95b1a2f819'
down_revision: Union[str, Sequence[str], None] = 'b746d7e4d267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('pandascore_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_leagues_pandascore_id'), 'leagues', ['pandascore_id'], unique=True)
    op.add_column('teams', sa.Column('pandascore_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teams_pandascore_id'), 'teams', ['pandascore_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_pandascore_id'), table_name='teams')
    op.drop_column('teams', 'pandascore_id')
    op.drop_index(op.f('ix_leagues_pandascore_id'), table_name='leagues')
    op.drop_column('leagues', 'pandascore_id')
    # ### end Alembic commands ###
