"""v1_5_add_streams_darkmode_location_tier

Revision ID: a3e0a2dfec3e
Revises: 8e95b1a2f819
Create Date: 2026-06-15 08:27:20.337609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e0a2dfec3e'
down_revision: Union[str, Sequence[str], None] = '8e95b1a2f819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('dark_mode_image_url', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('streams', sa.JSON(), nullable=True))
    op.add_column('matches', sa.Column('tier', sa.String(length=10), nullable=True))
    op.add_column('matches', sa.Column('prizepool', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('dark_mode_image_url', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('location', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'location')
    op.drop_column('teams', 'dark_mode_image_url')
    op.drop_column('matches', 'prizepool')
    op.drop_column('matches', 'tier')
    op.drop_column('matches', 'streams')
    op.drop_column('leagues', 'dark_mode_image_url')
    # ### end Alembic commands ###
