"""add_league_id_to_matches

Revision ID: aeb214e8e170
Revises: 905de1154264
Create Date: 2026-05-28 19:00:23.151149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb214e8e170'
down_revision: Union[str, Sequence[str], None] = '905de1154264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('league_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'leagues', ['league_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'league_id')
    # ### end Alembic commands ###
